version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5431:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=ranal_user
      - POSTGRES_DB=ranal_db

  migrate:
    image: rust:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://ranal_user:S3cret@postgres:5432/ranal_db
    depends_on:
      - postgres
    entrypoint: [ "sh", "-c", "cargo install sqlx-cli --features native-tls && sqlx migrate run" ]

volumes:
  db_data:
    driver: local
